server.port=8080
spring.application.name=schedule-backend

# Automatically import application-local.properties if it exists (ignored by Git)
spring.config.import=optional:classpath:application-local.properties

# Database Configuration (Injected via Environment Variables or application-local.properties)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
